-- The 18 products that shipped in src/lib/catalogue.ts. Stock starts uncounted (NULL), so they stay on sale
-- until the admin enters real counts. Safe to run twice: existing slugs are left alone.
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('run-machine', 'bat', 'bats', 'english-willow', 'Run Machine', NULL, NULL, NULL, 'Grade 4 English Willow', 'Grade 4 English Willow: 4 to 6 straight grains with some natural blemish and colour. Performance-first willow at an entry price.', 'Run Machine · Grade 4 English Willow · Sarawak cane handle with three rubber inserts · 40 mm edges · Astaad lion crest face sticker · supplied with a padded full-length cover.', 769900, 1099900, '{"enabled":true,"weights":["1120–1150 g","1150–1180 g","1180–1220 g"],"profiles":["Duckbill Players","Mid to Low","Full Spine"],"handles":["Round","Semi Oval","Oval"],"engraving":true,"matchReady":true,"scuffSheet":true}'::jsonb, '[]'::jsonb, false, 0) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/bat-english-willow.png', 0 FROM "products" WHERE "slug" = 'run-machine' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('combat-pro', 'bat', 'bats', 'english-willow', 'Combat Pro', NULL, NULL, NULL, 'Grade 3 English Willow', 'Grade 3 English Willow. Naturally air-dried and pressed for a lively face that only gets better.', 'Combat Pro · Grade 3 English Willow · Sarawak cane handle with three rubber inserts · 40 mm edges · Astaad lion crest face sticker · supplied with a padded full-length cover.', 979900, 1399900, '{"enabled":true,"weights":["1120–1150 g","1150–1180 g","1180–1220 g"],"profiles":["Duckbill Players","Mid to Low","Full Spine"],"handles":["Round","Semi Oval","Oval"],"engraving":true,"matchReady":true,"scuffSheet":true}'::jsonb, '[]'::jsonb, false, 1) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/bat-english-willow.png', 0 FROM "products" WHERE "slug" = 'combat-pro' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('black-edition', 'bat', 'bats', 'english-willow', 'Black Edition', NULL, NULL, NULL, 'Grade 2 English Willow', 'Grade 2 English Willow. Naturally air-dried and pressed for a lively face that only gets better.', 'Black Edition · Grade 2 English Willow · Sarawak cane handle with three rubber inserts · 40 mm edges · Astaad lion crest face sticker · supplied with a padded full-length cover.', 1259900, 2099900, '{"enabled":true,"weights":["1120–1150 g","1150–1180 g","1180–1220 g"],"profiles":["Duckbill Players","Mid to Low","Full Spine"],"handles":["Round","Semi Oval","Oval"],"engraving":true,"matchReady":true,"scuffSheet":true}'::jsonb, '[]'::jsonb, false, 2) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/bat-english-willow.png', 0 FROM "products" WHERE "slug" = 'black-edition' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('goat', 'bat', 'bats', 'english-willow', 'G.O.A.T', NULL, 'Greatest Of All Time', NULL, 'Grade 1 English Willow', 'Grade 1 English Willow. Naturally air-dried and pressed for a lively face that only gets better.', 'G.O.A.T · Grade 1 English Willow · Sarawak cane handle with three rubber inserts · 40 mm edges · Astaad lion crest face sticker · supplied with a padded full-length cover.', 1649900, 2999900, '{"enabled":true,"weights":["1120–1150 g","1150–1180 g","1180–1220 g"],"profiles":["Duckbill Players","Mid to Low","Full Spine"],"handles":["Round","Semi Oval","Oval"],"engraving":true,"matchReady":true,"scuffSheet":true}'::jsonb, '[]'::jsonb, false, 3) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/bat-english-willow.png', 0 FROM "products" WHERE "slug" = 'goat' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('the-godfather', 'bat', 'bats', 'english-willow', 'The Godfather', NULL, NULL, NULL, 'Grade 1+ Players English Willow', 'Grade 1+ Players English Willow. Naturally air-dried and pressed for a lively face that only gets better.', 'The Godfather · Grade 1+ Players English Willow · Sarawak cane handle with three rubber inserts · 40 mm edges · Astaad lion crest face sticker · supplied with a padded full-length cover.', 1979900, 3599900, '{"enabled":true,"weights":["1120–1150 g","1150–1180 g","1180–1220 g"],"profiles":["Duckbill Players","Mid to Low","Full Spine"],"handles":["Round","Semi Oval","Oval"],"engraving":true,"matchReady":true,"scuffSheet":true}'::jsonb, '[]'::jsonb, false, 4) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/bat-english-willow.png', 0 FROM "products" WHERE "slug" = 'the-godfather' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('legacy-one', 'bat', 'bats', 'english-willow', 'Legacy One', NULL, NULL, NULL, 'Top 1% of Grade 1+ Players English Willow', 'The top 1% of Grade 1+ Players English Willow. Naturally air-dried and pressed for a lively face that only gets better.', 'Legacy One · Top 1% of Grade 1+ Players English Willow · Sarawak cane handle with three rubber inserts · 40 mm edges · Astaad lion crest face sticker · supplied with a padded full-length cover.', 2309900, 4199900, '{"enabled":true,"weights":["1120–1150 g","1150–1180 g","1180–1220 g"],"profiles":["Duckbill Players","Mid to Low","Full Spine"],"handles":["Round","Semi Oval","Oval"],"engraving":true,"matchReady":true,"scuffSheet":true}'::jsonb, '["Top 1%"]'::jsonb, false, 5) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/bat-english-willow.png', 0 FROM "products" WHERE "slug" = 'legacy-one' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('elite-batting-gloves', 'gear', 'batting-gloves', NULL, 'Elite Batting Gloves', 'Elite', NULL, 'Pro sheepskin palm', NULL, NULL, NULL, 499900, NULL, NULL, '["Bestseller"]'::jsonb, true, 0) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/batting-gloves.png', 0 FROM "products" WHERE "slug" = 'elite-batting-gloves' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('pro-batting-gloves', 'gear', 'batting-gloves', NULL, 'Pro Batting Gloves', 'Pro', NULL, 'Split finger · right hand', NULL, NULL, NULL, 649900, NULL, NULL, '[]'::jsonb, false, 1) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/batting-gloves.png', 0 FROM "products" WHERE "slug" = 'pro-batting-gloves' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('players-batting-gloves', 'gear', 'batting-gloves', NULL, 'Players Batting Gloves', 'Players', NULL, 'Sausage finger · right hand', NULL, NULL, NULL, 849900, NULL, NULL, '[]'::jsonb, false, 2) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/batting-gloves.png', 0 FROM "products" WHERE "slug" = 'players-batting-gloves' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('pro-batting-pads', 'gear', 'batting-pads', NULL, 'Pro Batting Pads', 'Pro', NULL, 'Men’s · right hand', NULL, NULL, NULL, 549900, NULL, NULL, '[]'::jsonb, true, 3) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/batting-pads.png', 0 FROM "products" WHERE "slug" = 'pro-batting-pads' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('elite-batting-pads', 'gear', 'batting-pads', NULL, 'Elite Batting Pads', 'Elite', NULL, 'Men’s · ambidextrous', NULL, NULL, NULL, 749900, NULL, NULL, '[]'::jsonb, false, 4) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/batting-pads.png', 0 FROM "products" WHERE "slug" = 'elite-batting-pads' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('players-batting-pads', 'gear', 'batting-pads', NULL, 'Players Batting Pads', 'Players', NULL, 'Men’s · right hand', NULL, NULL, NULL, 999900, NULL, NULL, '[]'::jsonb, false, 5) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/batting-pads.png', 0 FROM "products" WHERE "slug" = 'players-batting-pads' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('club-cricket-helmet', 'gear', 'helmets', NULL, 'Club Cricket Helmet', 'Club', NULL, 'Steel grille · adjustable', NULL, NULL, NULL, 699900, NULL, NULL, '["Bestseller"]'::jsonb, true, 6) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/helmet.png', 0 FROM "products" WHERE "slug" = 'club-cricket-helmet' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('pro-cricket-helmet', 'gear', 'helmets', NULL, 'Pro Cricket Helmet', 'Pro', NULL, 'Steel grille · vented shell', NULL, NULL, NULL, 899900, NULL, NULL, '[]'::jsonb, false, 7) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/helmet.png', 0 FROM "products" WHERE "slug" = 'pro-cricket-helmet' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('elite-cricket-helmet', 'gear', 'helmets', NULL, 'Elite Cricket Helmet', 'Elite', NULL, 'Steel grille · lightweight shell', NULL, NULL, NULL, 1149900, NULL, NULL, '[]'::jsonb, false, 8) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/helmet.png', 0 FROM "products" WHERE "slug" = 'elite-cricket-helmet' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('pro-cricket-kitbag', 'gear', 'cricket-kitbags', NULL, 'Pro Cricket Kitbag', 'Pro', NULL, 'Wheelie · full kit', NULL, NULL, NULL, 349900, NULL, NULL, '["Bestseller"]'::jsonb, true, 9) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/kitbag.png', 0 FROM "products" WHERE "slug" = 'pro-cricket-kitbag' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('elite-cricket-kitbag', 'gear', 'cricket-kitbags', NULL, 'Elite Cricket Kitbag', 'Elite', NULL, 'Wheelie · full kit · bat sleeve', NULL, NULL, NULL, 549900, NULL, NULL, '[]'::jsonb, false, 10) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/kitbag.png', 0 FROM "products" WHERE "slug" = 'elite-cricket-kitbag' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
--> statement-breakpoint
INSERT INTO "products" ("slug", "kind", "category", "subcategory", "name", "line", "tagline", "note", "grade", "short_description", "description", "price_paise", "mrp_paise", "customization", "badges", "featured", "sort_order") VALUES ('players-cricket-kitbag', 'gear', 'cricket-kitbags', NULL, 'Players Cricket Kitbag', 'Players', NULL, 'Wheelie · two-kit · bat sleeve', NULL, NULL, NULL, 799900, NULL, NULL, '[]'::jsonb, false, 11) ON CONFLICT ("slug") DO NOTHING;
--> statement-breakpoint
INSERT INTO "product_images" ("product_id", "url", "position") SELECT "id", '/images/kitbag.png', 0 FROM "products" WHERE "slug" = 'players-cricket-kitbag' AND NOT EXISTS (SELECT 1 FROM "product_images" pi WHERE pi."product_id" = "products"."id");
